apiVersion: v1
kind: Pod
metadata:
  name: ambassador-example
spec:
  containers:
    - name: nginx
      image: nginx:latest
    - name: twemproxy
      image: ganomede/twemproxy:latest
      command:
        - "nutcracker"
        - "-c"
        - "/etc/config/nutcracker.yaml"
        - "-v"
        - "7"
        - "-s"
        - "6222"
      volumeMounts:
        - name: config-volume
          mountPath: /etc/config
  volumes:
    - name: config-volume
      configMap:
        name: twem-config
